### ISSUE TITLE
The variable _ is unbound

### ISSUE THREAD

**Issue by verti0** [eschulte/curry-compose-reader-macros#1]
I get the error "The variable _ is unbound" when entering this example:

``` lisp
(mapcar {- _ 1} '(1 2 3 4))
```

Examples without `_` give the expected results.
I have installed and enabled `curry-compose-reader-macros` with the following commands:

``` lisp
(ql:quickload "curry-compose-reader-macros")
(curry-compose-reader-macros:enable-curry-compose-reader-macros)
```

The compiler is sbcl.  Any idea what could be going wrong?

**Comment by eschulte** [comment]
You have to _use_ the `curry-compose-reader-macro` package for the `_` symbol to be defined.

```
CL-USER> (ql:quickload :curry-compose-reader-macros)
To load "curry-compose-reader-macros":
  Load 1 ASDF system:
    curry-compose-reader-macros
; Loading "curry-compose-reader-macros"
[package alexandria.0.dev]........................
[package curry-compose-reader-macros]
(:CURRY-COMPOSE-READER-MACROS)
CL-USER> (curry-compose-reader-macros:enable-curry-compose-reader-macros)
T
CL-USER> (mapcar {- _ 1} '(1 2 3 4))
; Evaluation aborted on #<UNBOUND-VARIABLE _ {1007FF4553}>.
CL-USER> (use-package :curry-compose-reader-macros)
; Evaluation aborted on #<NAME-CONFLICT {10082F2E53}>.
CL-USER> (unintern '_)
T
CL-USER> (use-package :curry-compose-reader-macros)
T
CL-USER> (mapcar {- _ 1} '(1 2 3 4))
(0 1 2 3)
CL-USER> 
```

**Comment by verti0** [comment]
Ah, I see.  Thanks for the help.

**Comment by bo-tato** [comment]
neat library, I also ran into same variable _ is unbound and found the solution here in closed issue. It would be good to mention in readme, the readme instructions just do in-readtable without mentioning to use _ symbol
